# Generated by Django 4.2.1 on 2023-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
