# Generated by Django 4.2.1 on 2023-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0004_rename_comment_comment_comments_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
