# Generated by Django 4.2.1 on 2023-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0005_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
