# Generated by Django 4.2.1 on 2023-05-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lekh.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
