# Generated by Django 4.2.1 on 2023-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0007_alter_comment_comments_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(default='', max_length=250),
        ),
    ]
