# Generated by Django 4.2.1 on 2023-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0008_alter_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(default='', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lekh.post'),
        ),
    ]
