# Generated by Django 4.2.1 on 2023-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekh', '0010_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
